name: Terraform CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./setup/terraform  # Adjust path if needed

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./setup/terraform  # Adjust path if needed
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}

      # Terraform Apply (only on main branch pushes)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./setup/terraform  # Adjust path if needed
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
