name: Terraform CD

on:
  workflow_dispatch:  # Enables manual execution only

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN || '' }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      # Initialize Terraform
      - name: Terraform Init
        working-directory: ./setup/terraform  # Adjust path if needed
        run: terraform init

      # Terraform Plan with Detailed Exit Code
      - name: Terraform Plan
        id: plan
        working-directory: ./setup/terraform  # Adjust path if needed
        continue-on-error: true  # Allow the job to continue even if this step fails
        shell: bash
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
        run: |
          terraform plan -detailed-exitcode -out=tfplan
          EXIT_CODE=$?
          echo "Terraform plan exit code: $EXIT_CODE"
          echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT

      # Terraform Apply if there are changes
      - name: Terraform Apply
        if: steps.plan.outputs.exitcode == '2'
        working-directory: ./setup/terraform  # Adjust path if needed
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve tfplan

      # No Changes Detected
      - name: No Changes to Apply
        if: steps.plan.outputs.exitcode == '0'
        run: echo "No changes to apply."

      # Handle Errors
      - name: Terraform Plan Error
        if: steps.plan.outputs.exitcode != '0' && steps.plan.outputs.exitcode != '2'
        run: echo "Error running terraform plan."
