name: Terraform Destroy

on:
  workflow_dispatch:  # Manually triggered

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{ secrets.AWS_REGION }}

      # Set up Terraform (use the version specified in your Terraform configuration)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./setup/terraform  # Adjust path if needed

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./setup/terraform  # Adjust path if needed


      # Terraform Destroy (Requires Confirmation)
      - name: Terraform Destroy
        run: terraform plan -destroy 
        working-directory: ./setup/terraform  # Adjust path if needed
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
